# """
# File: Configuration for research agent example in LOLA OS TMVP 1 Phase 4.

# Purpose: Provides configuration for the research agent.
# How: Defines YAML structure for API keys and settings.
# Why: Simplifies setup for example execution, per Developer Sovereignty.
# Full Path: lola-os/examples/research_agent/config.yaml
# """

pinecone_api_key: "your-pinecone-api-key"
openai_api_key: "your-openai-api-key"