# """
# File: Configuration for on-chain analyst agent example in LOLA OS TMVP 1 Phase 4.

# Purpose: Provides configuration for the on-chain analyst agent.
# How: Defines YAML structure for API keys and Web3 provider.
# Why: Simplifies setup for example execution, per Developer Sovereignty.
# Full Path: lola-os/examples/onchain_analyst/config.yaml
# """

openai_api_key: "your-openai-api-key"
web3_provider_uri: "http://localhost:8545"  # Or Sepolia testnet RPC