"""
File: Template configuration for React agent projects in LOLA OS TMVP 1 Phase 3.

Purpose: Provides default configuration for scaffolded React agent projects.
How: Defines YAML structure for API keys and settings.
Why: Simplifies project setup, per Developer Sovereignty.
Full Path: lola-os/python/lola/cli/templates/react/config.yaml
"""

pinecone_api_key: "your-pinecone-api-key"
openai_api_key: "your-openai-api-key"
web3_provider_uri: "http://localhost:8545"
redis_url: "redis://localhost:6379/0"